### ISSUE TITLE
Нет субтитров в видео с TED Talk

### ISSUE THREAD

**Issue by philip-bl** [effectivealtruism-ru/website#2]
Стоит либо использовать ютюб плеер и донести до читателя, что русские субтитры можно включить, либо прикрутить их как-то еще.

https://www.youtube.com/watch?v=Diuv3XZQXyc

В идеале чтобы английские субтитры тоже можно было включать. Мне например с ними лучше.

**Comment by berekuk** [comment]
Странно. Какой у тебя браузер? У меня в Chrome всё есть, и embed-код с сайта TED позволяет выбрать, какие сабы использовать.

**Comment by philip-bl** [comment]
У меня chrome в ubuntu. Плеер выглядит примерно так 
![2016-04-11 12-16-27](https://cloud.githubusercontent.com/assets/6838251/14422394/50872622-ffdf-11e5-96f6-fc2c539cff1e.png)

Включенные расширения, которые возможно что-то там делают:
- HTTPS Everywhere
- uBlock Origin

Надо будет потестировать без них. А если все равно нет, то потестировать в другой операционной системе.

**Comment by philip-bl** [comment]
На андроид планшете в firefox с теми же расширениями и в chrome нет субтитров.

![2016-04-11 09 53 55](https://cloud.githubusercontent.com/assets/6838251/14423526/f5a6036c-ffe4-11e5-8d03-dace6526c6ba.png)
![2016-04-11 09 55 55](https://cloud.githubusercontent.com/assets/6838251/14423527/f65c2d7c-ffe4-11e5-86b9-d10478b9c8d2.png)

**Comment by philip-bl** [comment]
lektor-embed-x для ютюб ссылки генерит `<iframe что-то-там/>`, и от этого исчезают все элементы после айфрейма. А если сделать `<iframe что-то-там></iframe>`, то все ок. Интересно.

**Comment by philip-bl** [comment]
https://stackoverflow.com/questions/27545757/why-is-a-self-closing-iframe-tag-preventing-further-dom-elements-to-be-displayed

lektor-embed-x надо бы допилить. Но лучше весь lektor просто закопать.

**Comment by philip-bl** [comment]
see https://github.com/kmonsoor/embedX/issues/4

**Comment by philip-bl** [comment]
Кто-то что-то сделал, или у меня субтитры появились из-за смены компьютера?

**Comment by berekuk** [comment]
Думаю, что из-за смены. Я вспомнил, что субтитры для ted-видео не работают для андроидодевайсов (знаю я это потому, что пытался показывать их с smarttv, и там была эта проблема).

**Comment by berekuk** [comment]
С youtube должно всё работать.
