### ISSUE TITLE
Когда происходит выкладывание на сайт?

### ISSUE THREAD

**Issue by philip-bl** [effectivealtruism-ru/website#6]
Непонятно. Пулл реквесты в мастер приняты, а сайт не обновлен.

**Comment by philip-bl** [comment]
Стоит это в ридми написать

**Comment by berekuk** [comment]
Должно было автоматически случиться, но что-то съехало с правами на деплой-бота.
Дописал в ридми, протестировал, теперь всё должно работать.

И кстати, послал тебе инвайт в организацию.
