### ISSUE TITLE
Репозиторий не актуален. Может удалить его?

### ISSUE THREAD

**Issue by philip-bl** [effectivealtruism-ru/website#9]
Я обнаружил ошибку на https://effectivealtruism.ru, пошел сюда исправить и обнаружил, что этот репозиторий уже не используется. Может удалить его или пометить, что оне не используется?

**Comment by berekuk** [comment]
Заархивировал репозиторий, спасибо.

Связаться с командой сайта можно теперь с помощью этой формы: https://effectivealtruism.ru/contact/
